@startuml
'skinparam linetype ortho

folder "OpenStack Test Double" as openstack #orange {
    component "OpenStack API" <<Mock Service>> as api #yellow

    database "OpenStack DB" <<Optional/In-memory>> as db
'    note top of db #red
'    Not yet implemented.
'    endnote

    queue "RabbitMQ" as amqp
'    note top of amqp #red
'    Not yet implemented.
'    endnote

    api .right-> db : Persist/Retrieve\n"fake" Resources
    api .left-> amqp : Change Events\n(like Ceilometer)
}
note top of openstack #red
Should look to the outside, e.g.,
arbitrary clients, like a "real"
OpenStack implementation.
endnote

control "Client 1" as client1
note left
Could also be a/the (default)
CLI or Web-UI
endnote
client1 .-> api : Manage\nResources

'folder "Our Development" as dev {
'component "Other System" as other #lightgreen {
  control "Client 2" as client2

  amqp .down-> client2 : Forward\nEvents
  client2 -down-> api : Retrieve\nResources
'}

note right of client2 #lightgreen
System under Test (SuT)
endnote

'component "Test Driver" as driver #lightblue
'driver --up-> api : Manage\nTest Resources
'driver -left-> other : Test Behavior

'dev --up[hidden]- openstack : Test Behavior
'}
@enduml