name: Build and Publish Docker Image

on:
  push:
    branches: ['**']
    tags: ['*']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to get tags for main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        # For some reason, pushing is not working with buildx as of 2025-08-25
        run: |
          set -euo pipefail
          IMAGE="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/openstack-mock" make docker-build
